### ISSUE TITLE
Use matrix of [v6m, v7m] in CI.

### ISSUE THREAD

**Issue by bmarcot** [bmarcot/vega#14]
Add to .travis.yml:

```
matrix:
  include:
    - env: PLATFORM=qemu
    - env: PLATFORM=microbit

```

And getenv() in Python test runner.
